"""add_detailed_agent_specifications_to_sessions

Revision ID: 2eaea2233f87
Revises: 49dbb0c81740
Create Date: 2025-10-05 01:19:21.041793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2eaea2233f87"
down_revision: Union[str, None] = "49dbb0c81740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to sessions table
    op.add_column("sessions", sa.Column("agent_type", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("goals", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("tone", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("target_users", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("greeting_style", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("conversation_flow", sa.Text(), nullable=True))
    op.add_column(
        "sessions", sa.Column("example_interactions", sa.Text(), nullable=True)
    )
    op.add_column("sessions", sa.Column("constraints", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("edge_cases", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("escalation_rules", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("success_criteria", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("brand_voice", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("verbosity_level", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("additional_notes", sa.Text(), nullable=True))
    op.add_column("sessions", sa.Column("use_tools", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove columns from sessions table
    op.drop_column("sessions", "use_tools")
    op.drop_column("sessions", "additional_notes")
    op.drop_column("sessions", "verbosity_level")
    op.drop_column("sessions", "brand_voice")
    op.drop_column("sessions", "success_criteria")
    op.drop_column("sessions", "escalation_rules")
    op.drop_column("sessions", "edge_cases")
    op.drop_column("sessions", "constraints")
    op.drop_column("sessions", "example_interactions")
    op.drop_column("sessions", "conversation_flow")
    op.drop_column("sessions", "greeting_style")
    op.drop_column("sessions", "target_users")
    op.drop_column("sessions", "tone")
    op.drop_column("sessions", "goals")
    op.drop_column("sessions", "agent_type")
    # ### end Alembic commands ###
