"""add_prompt_exports_table

Revision ID: 49dbb0c81740
Revises: 8f60079955c3
Create Date: 2025-10-04 23:36:04.024001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49dbb0c81740'
down_revision: Union[str, None] = '8f60079955c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_exports_id', table_name='prompt_exports')
    op.drop_index('ix_prompt_exports_session_id', table_name='prompt_exports')
    op.drop_table('prompt_exports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_exports',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('export_format', postgresql.ENUM('JSON', 'YAML', 'MARKDOWN', 'TEXT', name='exportformat'), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='prompt_exports_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prompt_exports_pkey')
    )
    op.create_index('ix_prompt_exports_session_id', 'prompt_exports', ['session_id'], unique=False)
    op.create_index('ix_prompt_exports_id', 'prompt_exports', ['id'], unique=False)
    # ### end Alembic commands ###
